export const timeQuotes = [{ quote: 'The two most powerful warriors are patience and time.', author: 'Leo Tolstoy' },
  { quote: 'Time is what we want most, but what we use worst.', author: 'William Penn' },
  { quote: 'All we have to decide is what to do with the time that is given us.', author: 'J.R.R. Tolkien' },
  { quote: 'The most precious resource we all have is time.', author: 'Steve Jobs' },
  { quote: 'Time has a wonderful way of showing us what really matters.', author: 'Margaret Peters' },
  { quote: 'Time is a created thing. To say ‘I don’t have time’ is to say "I don’t want to."', author: 'Lao Tzu' },
  { quote: 'No man goes before his time. Unless the boss leaves early.', author: 'Groucho Marx' },
  { quote: 'Time is free, but it’s priceless. You can’t own it, but you can use it. You can’t keep it, but you can spend it. Once you’ve lost it, you can never get it back.', author: 'Harvey MacKay' },
  { quote: 'The future is something which everyone reaches at the rate of sixty minutes an hour, whatever he does, whoever he is.', author: 'C.S. Lewis' },
  { quote: 'The bad news is time flies. The good news is you’re the pilot.', author: 'Michael Altshuler' },
  { quote: 'There’s only one thing more precious than our time and that’s who we spend it on.', author: 'Leo Christopher' },
  { quote: 'An inch of time is an inch of gold, but you can’t buy that inch of time with an inch of gold.', author: 'Chinese Proverb' },
  { quote: 'There’s never enough time to do it right, but there’s always enough time to do it over.', author: 'Jack Bergman' },
  { quote: 'A man who dares to waste an hour of time has not discovered the value of life.', author: 'Charles Darwin' },
  { quote: 'Time isn’t the main thing. It’s the only thing.', author: 'Miles Davis' },
  { quote: 'I am not particularly interested in saving time; I prefer to enjoy it.', author: 'Eduardo Galeano' },
  { quote: 'Time flies over us, but leaves its shadow behind.', author: 'Nathaniel Hawthorne' },
  { quote: 'Time is what keeps everything from happening at once.', author: 'Ray Cummings' },
  { quote: 'It’s not that we have little time, but more that we waste a good deal of it.', author: 'Seneca' },
  { quote: 'I wish I could turn back the clock and find you sooner so I can love you longer.', author: 'Unknown author' },
  { quote: 'Time moves slowly, but passes quickly.', author: 'Alice Walker' },
  { quote: 'You will never find time for anything. If you want time, you must make it.', author: 'Charles Buxton' },
  { quote: 'There’s never enough time to do all the nothing you want.', author: 'Bill Watterson' },
  { quote: 'They always say time changes things, but you actually have to change them yourself.', author: 'Andy Warhol' },
  { quote: 'Time is a waste of money.', author: 'Oscar Wilde' },
  { quote: 'Time is a great healer, but a poor beautician.', author: 'Lucille S. Harper' },
  { quote: 'No measure of time with you will be long enough. But let’s start with forever.', author: 'Stephenie Meyer' },
  { quote: 'You can’t turn back the clock. But you can wind it up again.', author: 'Bonnie Prudden' },
  { quote: 'Time has no meaning when you’re in love.', author: 'Unknown author' },
  { quote: 'Better three hours too soon than one minute too late.', author: 'William Shakespeare' },
  { quote: 'There is never a time or place for true love. It happens accidentally, in a heartbeat, in a single flashing, throbbing moment.', author: 'Sarah Dessen' },
  { quote: 'There is a time for work and a time for love. That leaves no other time.', author: 'Coco Chanel' },
  { quote: 'Time is the longest distance between two places.', author: 'Tennessee Williams' },
  { quote: 'To live is so startling, it leaves little time for anything else.', author: 'Emily Dickinson' },
  { quote: 'Lost time is never found again.', author: 'Benjamin Franklin' },
  { quote: 'The only reason for time is so that everything doesn’t happen at once.', author: 'Albert Einstein' },
  { quote: 'Time you enjoy wasted was not time wasted.', author: 'John Lennon' },
  { quote: 'Time is precious. Make sure you spend it with the right people.', author: 'Unknown author' },
  { quote: 'Who controls the past, controls the future: who controls the present controls the past.', author: 'George Orwell' },
  { quote: 'Time, which changes people, does not alter the image we have of them.', author: 'Marcel Proust' },
  { quote: 'Own time, or time will own you.', author: 'Brian Norgard' }];

export const getRandomQuote = () => timeQuotes[Math.floor(Math.random() * timeQuotes.length)];
